services:
  db:
    image: postgres:18.0-trixie
    container_name: celan_db
    restart: unless-stopped
    ports:
      - 5435:5432
    env_file:
      - .env
    volumes:
      - ./pgdata18:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB -h 127.0.0.1 -q" ]
      interval: 10s
      timeout: 5s
      retries: 5

  django_celan:
    container_name: django_celan
    restart: unless-stopped
    build:
      context: .
    tty: true  # Enable terminal allocation
    stdin_open: true  # Keep stdin open for interactive input
    env_file:
      - .env
    volumes:
      - ./:/app
      - ./backups:/backups
    ports:
      - 8004:8000
    depends_on:
      db:
        condition: service_healthy

  react_celan:
    container_name: react_celan
    build: ./frontend
    restart: unless-stopped
    ports:
      - 3002:5173
    volumes:
      - ./frontend:/app
      - /app/node-modules
    environment:
        - CHOKIDAR_USEPOLLING=true
    depends_on:
      - django_celan 
